const appwriteConfig = {
  ENDPOINT: import.meta.env.VITE_APPWRITE_ENDPOINT,
  PROJECT_ID: import.meta.env.VITE_APPWRITE_PROJECT_ID,
  DATABASE_ID: import.meta.env.VITE_APPWRITE_DATABASE,
  USER_COLLECTION: import.meta.env.VITE_APPWRITE_USER_COLLECTION,
  INVENTORY_COLLECTION: import.meta.env.VITE_APPWRITE_INVENTORY_COLLECTION,
  SALES_COLLECTION: import.meta.env.VITE_APPWRITE_SALES_COLLECTION,
  EXPENSES_COLLECTION: import.meta.env.VITE_APPWRITE_EXPENSES_COLLECTION,
};

export { appwriteConfig };
