const appwriteConfig = {
  ENDPOINT: import.meta.env.VITE_APPWRITE_ENDPOINT,
  PROJECT_ID: import.meta.env.VITE_APPWRITE_PROJECT_ID,
  DATABASE_ID: import.meta.env.VITE_APPWRITE_DATABASE,
  USER_COLLECTION: import.meta.env.VITE_APPWRITE_USER_COLLECTION,
  INVENTORY_COLLECTION: import.meta.env.VITE_APPWRITE_INVENTORY_COLLECTION,
  SALES_COLLECTION: import.meta.env.VITE_APPWRITE_SALES_COLLECTION,
  EXPENSES_COLLECTION: import.meta.env.VITE_APPWRITE_EXPENSES_COLLECTION,
  STORAGE_ID: import.meta.env.VITE_APPWRITE_STORAGE_ID,
  ADMIN_COLLECTION: import.meta.env.VITE_APPWRITE_ADMIN_COLLECTION,
};

export const {
  ENDPOINT,
  PROJECT_ID,
  DATABASE_ID,
  USER_COLLECTION,
  INVENTORY_COLLECTION,
  SALES_COLLECTION,
  EXPENSES_COLLECTION,
  STORAGE_ID,
  ADMIN_COLLECTION,
} = appwriteConfig;
